
#ifndef __PACKET_ENUMERATIONS_H
#define __PACKET_ENUMERATIONS_H

enum
{
	ID_CONNECTION_REQUEST_ACCEPTED = 16,

	ID_NEW_INCOMING_CONNECTION = 18,
	ID_NO_FREE_INCOMING_CONNECTIONS,
	ID_DISCONNECTION_NOTIFICATION,
	ID_CONNECTION_LOST,

	ID_CONNECTION_BANNED = 23,
	ID_INVALID_PASSWORD,
	ID_MODIFIED_PACKET,

	ID_PLAYER_SYNC = 82,

	ID_VEHICLE_SYNC = 84,

	ID_PASSENGER_SYNC = 86,
	ID_AIM_SYNC,
	ID_RCON_COMMAND,
};

#endif
