
#include "main.h"

RakServerInterface		*pRak=0;

//----------------------------------------------------

void UnRegisterRPCs(RakServerInterface * pRakServer)
{
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, ClientJoin);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, ClientJoinPatch);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, Chat);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, ME);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, MsgChat);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, TeamChat);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, RequestClass);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, Spawn);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, Death);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, EnterVehicle);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, ExitVehicle);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, UpdateScoreAndPing);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, Admin);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, KickPlayer);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, BanIPAddress);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, Ban);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, Set);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, SetA);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, Quit);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, QuitA);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, PickedUp);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, DoAnim);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, Spec);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, RequestAmmu);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, RequestWep);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, Commanda);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, SetMin);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, SetHr);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, SetWeather);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, SetTimeRate);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, PlayerDied);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, PlayerFell);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, CrashDump);
	UNREGISTER_AS_REMOTE_PROCEDURE_CALL(pRakServer, SendSpikeStrip);

	pRak = 0;
}

//----------------------------------------------------
